Algoritmo "EstruturaEnquanto"
// Disciplina  : [Algaritimos e Lógica de Programação]
// Professor   : NILTON CESAR SACCO
// Descrição   : Repetições
// Autor(a)    : Daniel de Godoy Carolino
// Data atual  : 06/04/2022
Var
   nome : caracter
   cont : inteiro

Inicio
   cont := 0
   escreval("Me diga seu nome: ")
   leia(nome)
   escreval()

   enquanto (cont < 10) faça
      escreval("olá, ", nome,)

      cont := cont + 1
   fimenquanto

Fimalgoritmo